import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "com.teamshryne.wediyo"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.teamshryne.wediyo"
        minSdk = 21 // HIGHLY COMPATIBLE: covers Android 5.0+ (~99.5% devices in 2026)
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }

        // NDK: keep API 21 for max compatibility
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            isMinifyEnabled = false
            applicationIdSuffix = ".debug"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    packaging {
        jniLibs {
            useLegacyPackaging = false
        }
    }

    // UniFFI: COMMITTED bindings at src/main/kotlin/uniffi (generated by rust workflow)
    // Fallback ephemeral dir build/generated/uniffi is also on source path for ad-hoc local gen,
    // but APK workflow uses committed one — no regen needed on every app change.
    sourceSets {
        getByName("main") {
            kotlin.srcDirs("src/main/kotlin", "build/generated/uniffi")
            jniLibs.srcDirs("src/main/jniLibs")
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)

    // Go gomobile AAR (preferred — fast builds) — committed by go.yml to app/libs/wediyo.aar
    // If file exists, use it; fallback to Rust jniLibs otherwise.
    if (file("libs/wediyo.aar").exists()) {
        implementation(files("libs/wediyo.aar"))
    }

    // UniFFI runtime (JNI) — for Rust legacy (keep while migrating)
    implementation("net.java.dev.jna:jna:5.14.0@aar")

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}

// ---------------------------------------------------------------------------
// Rust + UniFFI integration — MANUAL ONLY, not wired to preBuild
//
// Policy split (per user request):
//   - Rust workflow (.github/workflows/rust.yml) builds libs + UniFFI Kotlin bindings
//     and COMMITS them to `app/src/main/jniLibs/` + `app/src/main/kotlin/uniffi/`
//   - Android workflow (.github/workflows/android.yml) just runs ./gradlew —
//     it USES committed artifacts, does NOT rebuild Rust on every app change.
//
// Keeping these tasks defined lets you run them manually on CI via:
//   ./gradlew cargoBuild   or   ./gradlew uniffiBindgen
// but `preBuild` does NOT depend on them, so APK builds don't regen bindings
// just because you touched `rust/`.
// ---------------------------------------------------------------------------

val rustCrateDir = file("../rust/wediyo_engine")
val jniLibsDir = file("src/main/jniLibs")
val committedUniffiDir = file("src/main/kotlin/uniffi")
val ephemeralUniffiDir = file("build/generated/uniffi")

val cargoBuild by tasks.registering(Exec::class) {
    description = "Build Rust crate for Android targets via cargo-ndk (manual — see rust.yml)"
    group = "rust"
    workingDir(rustCrateDir)
    commandLine(
        "cargo", "ndk",
        "-t", "arm64-v8a",
        "-t", "armeabi-v7a",
        "-t", "x86_64",
        "-o", jniLibsDir.absolutePath,
        "build", "--release"
    )
    onlyIf { System.getenv("CI") == "true" || file("/home/shrawan/.cargo/bin/cargo-ndk").exists() }
    doFirst { jniLibsDir.mkdirs() }
}

val cargoBuildCommit by tasks.registering(Exec::class) {
    description = "Build + generate COMMITTED UniFFI — called by rust.yml"
    group = "rust"
    workingDir(rustCrateDir)
    // This is a convenience umbrella; actual CI calls cargo ndk + uniffi-bindgen directly
    commandLine("echo", "use rust.yml workflow; do not call locally — machine is bad")
}

val uniffiBindgen by tasks.registering(Exec::class) {
    description = "Generate Kotlin bindings via uniffi-bindgen to COMMITTED dir (manual)"
    group = "rust"
    workingDir(rustCrateDir)
    // For proc-macro UniFFI, bindgen inspects compiled .so for metadata.
    // Uses arm64 lib as representative (goblin parses it on x86 host).
    val arm64Lib = jniLibsDir.resolve("arm64-v8a/libwediyo_engine.so")
    // Default to committed dir; rust.yml will call with explicit --out-dir
    commandLine(
        "cargo", "run", "--bin", "uniffi-bindgen",
        "generate",
        "--library", arm64Lib.absolutePath,
        "--language", "kotlin",
        "--out-dir", committedUniffiDir.absolutePath
    )
    onlyIf { arm64Lib.exists() || System.getenv("CI") == "true" }
    doFirst {
        committedUniffiDir.mkdirs()
        ephemeralUniffiDir.mkdirs()
    }
}

// ---------------------------------------------------------------------------
// Go + gomobile integration — preferred (fast)
//   go.yml builds app/libs/wediyo.aar via `gomobile bind -target=android -androidapi 21`
//   and commits it. APK workflow just uses committed AAR. Local machine is bad
//   so don't run gomobile locally without NDK.
// ---------------------------------------------------------------------------
val goDir = file("../go/wediyo")
val goAar = file("libs/wediyo.aar")
val gomobileBind by tasks.registering(Exec::class) {
    description = "Build Go AAR via gomobile bind (manual — see go.yml)"
    group = "go"
    workingDir(goDir)
    commandLine(
        "gomobile", "bind",
        "-target=android",
        "-androidapi", "21",
        "-javapkg", "com.teamshryne.wediyo",
        "-o", goAar.absolutePath,
        "."
    )
    onlyIf { System.getenv("CI") == "true" || file("/home/shrawan/go/bin/gomobile").exists() }
    doFirst { file("libs").mkdirs() }
}

// NOTE: preBuild does NOT depend on cargoBuild/uniffiBindgen/gomobileBind by design.
// APK workflow uses committed libs/bindings/AAR. Workflows commit new ones.
